### ISSUE TITLE
low sdcard memory means no peers

### ISSUE THREAD

**Issue by eri451** [schildbach/bitcoin-wallet#273] opened 2015-11-22 17:54 UTC
![wat?](http://www.troll.me/images/jackie-chan-whut/wat.jpg "wat?")

I did not use but constantly updated the app for quite some time. Today though I expected some BTC to arrive. The sender assured me that he paid but it simply not show up.
After I found out that I don't have peers, even after editing the "trustfully peers" I asked my BTC-Buddy why.

It seems that the app is not working if you have not enough space on the sd card. Yes I have more then one app. So I constantly ignored the "Delete all other app but mine"-popup, that why ever leads to the app settings instead of leading to the memory settings.

Somewhere I read, that my coins are in danger if I don't have enough space. But there was no single word about how much space is actually needed. In stead it the app working as expected but has no sync.

This is very bad user experience.
Warnings about backups and security all over the place but no error reports with some helpful messages at all.

After making some space by deleting stuff and seeing no effect I finally reinstalled the app and recovered my wallet. I'm still waiting for sync.

Sorry that some people are not able to figure out what sdcard space has to do with networking

**Comment by schildbach** [comment] 2015-11-22 20:43
It would be useful to know if your "external storage" is on the same filesystem as your internal storage. If your device doesn't have a physical SD card slot, it is very likely to share the filesystem. In this case the issue is simply internal storage space. Your issue description seems to imply that you've seen the "low storage warning".

The app needs storage space to work. If it runs out, it will get into an undefined state. Which can, although it's very unlikely, put your coins in danger. But it could easily happen that you could not add a single transaction, preventing you from sending even the already confirmed coins out. So we decided to stop receiving blocks as soon as memory is low. Yes, it will prevent you from seeing any received coins from this point on.

All you should need to do is free some space. It's up to you if you remove e.g. some media from the external storage (if it is shared with internal storage) or if you remove some apps.

**Comment by eri451** [comment] 2015-12-14 17:22
Yes my device has a physical SD card slot.
"All you should need to do is free some space". Yes that helped but for how long? You see I'd like to keep my Podcast, pictures, which is currently not possible, because it is not clear how much "some" actually is.
Is there data how much space the app at least needs to work?

**Comment by schildbach** [comment] 2015-12-14 17:29
On my device it currently takes 2.5 MB for *data*. That's a wallet with lots of transactions, created 4 years ago.

I'll close this issue now. The app works as designed.

**Closed by schildbach** 2015-12-14 17:29 UTC
