### ISSUE TITLE
Support fee bumping in the UI

### ISSUE THREAD

**Issue by btcdrak** [schildbach/bitcoin-wallet#238] opened 2015-06-20 20:11 UTC
[First seen safe replace-by-fee](http://www.mail-archive.com/bitcoin-development%40lists.sourceforge.net/msg07829.html) is now actively mined by f2pool (21% of the network hash) and we can expect more pools to support this soon. The feature allows users to increase the fee of an existing transaction and rebroadcast it. This offers the possibility of significant usability improvements for bitcoin users who send a transaction with an insufficient fee, or at a time when the network is busy confirming spam transactions, can now rebroadcast with a higher fee to bump the priority. No more stuck transactions.

code can be found here: https://github.com/bitcoin/bitcoin/pull/6176

**Comment by noconfirm** [comment] 2015-07-09 23:41
Something like this is needed badly. The fee is too low now and if one of your addresses has dust that gets included you're screwed. 

I have multiple 0.25 transactions stuck right now.  (going on 4 days.) I checked Blockchain.info and they dropped after 2 days but I was stupid and reopened android wallet and it rebroadcast the transactions. And now i gotta wait another 2 days before they drop again. I keep getting the Medium Priority confirmation warnings on Blockchain.info  "This transaction has an output less than 0.01 BTC but doesn't include a fee."

I think I'm going to have to import andorid wallet into another client so I can resend with a higher fee after they drop.

**Comment by schildbach** [comment] 2015-07-10 08:14
@noconfirm Bitcoin transactions cannot simply be made forgotten by the network like that. As long as they're valid and standard, they will live on and get rebroadcasted back to you. Until they're included in a block.

**Comment by noconfirm** [comment] 2015-07-10 14:08
@schildbach Then why are unconfirmed transactions disappearing off of blockchain.info after a couple days? I thought the memory pool only holds so many IOU's. The transaction gets rebroadcasted by the sender if he opens his client yes. I watched my transaction reappear and the timestamp get updated on blockchain.info when I reconnected.

Actually the bitcoin memory pool thing has me worried now. All the spam transactions taking place this week could bring bitcoin to a slow crawl where even high priority/huge fee transactions take days to confirm.

**Comment by schildbach** [comment] 2015-07-10 14:15
Blockchain.info do their own thing. They are not relevant, they're just one node of the thousands of Bitcoin P2P nodes. The memory pool is distributed between these nodes. If one node forgets (easy – just shut down the node), it will get reminded by the others.

One method of fee bumping I'd like to support is CPFP (child pays for parent). However as far as I know only a tiny ~5% fraction of the hashing power supports this.

**Comment by petertodd** [comment] 2015-07-11 10:38
%18 (F2Pool) supports FSS-RBF and that will soon rise to %30 as BTCChina is working on implementing it.

CPFP for fee bumping is significantly more expensive than FSS-RBF, let alone full-RBF. It's also less reliable as the P2P protocol has no way of "combining" transactions; there's no guarantee the first tx got to the miners so the second tx bumping the fee may be entirely ignored.

**Comment by schildbach** [comment] 2015-07-11 10:57
However if I understand right, FSS-RBF cannot be used by the *recipient* of the transaction to be fee-bumped. But that's what is needed most currently.

**Comment by petertodd** [comment] 2015-07-11 11:01
Depends!

For instance, all exchanges I've ever used simply don't count transactions until they confirm; the transaction is considered complete after x confirms, not before. The same applies to ATM's and the like. Only in the rare case of a recipient who trusts the sender not to double-spend them is it the other way around, which is particularly true with consumer-facing wallets.

**Comment by schildbach** [comment] 2015-11-03 15:19
CPFP is supported since a while, so I'm closing this issue.

**Closed by schildbach** 2015-11-03 15:19 UTC
Labels: enhancement
