### ISSUE TITLE
Please add HTTP proxy support.

### ISSUE THREAD

**Issue by espress0** [schildbach/bitcoin-wallet#255] opened 2015-09-21 08:25 UTC
I need to use HTTP proxy to connect outside my network.
Please add HTTP proxy option, like F-Droid.
(And before you ask - I don't want to use Android Wifi's "System Proxy" function.)

[X] Enable HTTP Proxy
Proxy Host: xxxxx
Proxy Port: xxxxx

**Comment by schildbach** [comment] 2015-11-03 15:22
Duplicate of #173

**Closed by schildbach** 2015-11-03 15:22 UTC
Labels: duplicate, enhancement
